2023-08-09 10:45:29,248 ERROR: Exception on /register [GET] [in /Users/dc/test_stuff/flask/ch11/microblog/.ch11venv/lib/python3.11/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/dc/test_stuff/flask/ch11/microblog/.ch11venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dc/test_stuff/flask/ch11/microblog/.ch11venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dc/test_stuff/flask/ch11/microblog/.ch11venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dc/test_stuff/flask/ch11/microblog/.ch11venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dc/test_stuff/flask/ch11/microblog/app/routes.py", line 107, in register
    return render_template('register.html', title="Registration", form=form)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dc/test_stuff/flask/ch11/microblog/.ch11venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dc/test_stuff/flask/ch11/microblog/.ch11venv/lib/python3.11/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dc/test_stuff/flask/ch11/microblog/.ch11venv/lib/python3.11/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dc/test_stuff/flask/ch11/microblog/.ch11venv/lib/python3.11/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dc/test_stuff/flask/ch11/microblog/.ch11venv/lib/python3.11/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dc/test_stuff/flask/ch11/microblog/.ch11venv/lib/python3.11/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/Users/dc/test_stuff/flask/ch11/microblog/.ch11venv/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/dc/test_stuff/flask/ch11/microblog/app/templates/register.html", line 2, in template
    {%import 'bootstrap/wtf.html as wtf%}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.TemplateSyntaxError: unexpected char "'" at 35
2023-08-09 10:45:58,633 INFO: microblog startup [in /Users/dc/test_stuff/flask/ch11/microblog/app/__init__.py:42]
2023-08-09 10:50:57,265 INFO: microblog startup [in /Users/dc/test_stuff/flask/ch12/microblog/app/__init__.py:42]
2023-08-09 11:01:42,509 INFO: microblog startup [in /Users/dc/test_stuff/flask/ch12/microblog/app/__init__.py:42]
2023-08-09 11:20:00,433 INFO: microblog startup [in /Users/dc/test_stuff/flask/ch12/microblog/app/__init__.py:44]
2023-08-09 11:20:05,789 ERROR: Exception on / [GET] [in /Users/dc/test_stuff/flask/ch12/microblog/.ch12venv/lib/python3.11/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/dc/test_stuff/flask/ch12/microblog/.ch12venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dc/test_stuff/flask/ch12/microblog/.ch12venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dc/test_stuff/flask/ch12/microblog/.ch12venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dc/test_stuff/flask/ch12/microblog/.ch12venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dc/test_stuff/flask/ch12/microblog/.ch12venv/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dc/test_stuff/flask/ch12/microblog/app/routes.py", line 45, in index
    return render_template('index.html', title="Explore",form=form, posts=posts.items, next_url = next_url, prev_url=prev_url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dc/test_stuff/flask/ch12/microblog/.ch12venv/lib/python3.11/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dc/test_stuff/flask/ch12/microblog/.ch12venv/lib/python3.11/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dc/test_stuff/flask/ch12/microblog/.ch12venv/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/dc/test_stuff/flask/ch12/microblog/.ch12venv/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/dc/test_stuff/flask/ch12/microblog/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dc/test_stuff/flask/ch12/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dc/test_stuff/flask/ch12/microblog/.ch12venv/lib/python3.11/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/dc/test_stuff/flask/ch12/microblog/.ch12venv/lib/python3.11/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/Users/dc/test_stuff/flask/ch12/microblog/.ch12venv/lib/python3.11/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/Users/dc/test_stuff/flask/ch12/microblog/.ch12venv/lib/python3.11/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 26, in block 'body'
    {% block scripts %}
  File "/Users/dc/test_stuff/flask/ch12/microblog/app/templates/base.html", line 9, in block 'scripts'
    {{moment_include_moment()}}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dc/test_stuff/flask/ch12/microblog/.ch12venv/lib/python3.11/site-packages/jinja2/utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'moment_include_moment' is undefined
2023-08-09 11:21:13,648 INFO: microblog startup [in /Users/dc/test_stuff/flask/ch12/microblog/app/__init__.py:44]
